allowlist:
  - ""

openai-api-key: ""

text_command_aliases:
  - chatgpt
  - gpt

image_command_aliases:
  - dalle
  - imgai

images_to_generate: 2
image_output_size: "1024x1024"

text_ai_model: text-davinci-003
text_ai_model_temperature: 0.7  # Accepts floats between 0-1
text_ai_model_max_tokens: 256 # Accepts up to 4000
text_ai_model_top_p: 1 # Accepts floats between 0-1
text_ai_model_frequency_penalty: 0 # accepts values 0-2. Accepts floats
text_ai_model_presence_penalty: 0 # accepts values 0-2. Accepts floats
text_ai_debug: false
text_ai_use_chat_endpoint: false

text_ai_base_url: https://api.openai.com
image_ai_base_url: https://api.openai.com